# Generated by Django 4.2.7 on 2023-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carros", "0003_remove_carros_em_uso_carros_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carros",
            name="ativo",
            field=models.BooleanField(default=False, verbose_name="ativo"),
        ),
    ]
