# Generated by Django 4.2.7 on 2023-12-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pilotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_de_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="nome da equipe"),
                ),
                (
                    "nacionalidade",
                    models.CharField(max_length=200, verbose_name="nacionalidade"),
                ),
                (
                    "data_de_nascimento",
                    models.DateField(verbose_name="data de nascimento"),
                ),
                (
                    "detalhes",
                    models.TextField(blank=True, null=True, verbose_name="detalhes"),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="ativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Piloto",
                "verbose_name_plural": "Pilotos",
                "ordering": ["nome"],
            },
        ),
    ]
