# Generated by Django 4.2.7 on 2023-12-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carros_equipe'),
        ('pilotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotos',
            name='carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carros.carros', verbose_name='carro'),
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='nome do piloto'),
        ),
    ]
