# Generated by Django 4.2.7 on 2023-12-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0002_pilotos_carro_alter_pilotos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotos',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
    ]
