# Generated by Django 4.2.7 on 2023-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pilotos", "0004_alter_pilotos_nacionalidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotos",
            name="ativo",
            field=models.BooleanField(default=False, verbose_name="ativo"),
        ),
    ]
