# Generated by Django 4.2.7 on 2023-12-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_de_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="nome da equipe"),
                ),
                (
                    "detalhes",
                    models.TextField(blank=True, null=True, verbose_name="detalhes"),
                ),
                (
                    "fundador",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="nome do fundador",
                    ),
                ),
                (
                    "administrador",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="nome do administrador",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="ativa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
                "ordering": ["nome"],
            },
        ),
    ]
