# Generated by Django 4.2.7 on 2023-12-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipes",
            name="ativa",
            field=models.BooleanField(default=False, verbose_name="ativa"),
        ),
    ]
