# Generated by Django 4.2.7 on 2023-12-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipes", "0002_alter_equipes_ativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipes",
            name="ativa",
            field=models.BooleanField(blank=True, default=False, verbose_name="ativa"),
        ),
    ]
