# Generated by Django 4.2.7 on 2023-12-07 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipes", "0005_alter_equipes_ativa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipes",
            options={
                "ordering": ["nome"],
                "permissions": [("can_delete_equipe", "Can delete Equipe")],
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
            },
        ),
    ]
